version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"      
      timezone: "Europe/Paris"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
      day: "saturday"
      time: "08:00"      
      timezone: "Europe/Paris"