name: myyoukounkoun
description: New flutter project with basics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.25.4
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.19
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  intl: ^0.18.1
  country_code_picker: ^3.0.0
  image_picker: ^1.0.7
  colorful_safe_area: ^1.0.0
  url_launcher: ^6.2.5
  package_info_plus: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^8.0.1
  flag: ^7.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  connectivity_plus: ^5.0.2
  age_calculator: ^1.0.0
  top_snackbar_flutter: ^3.1.0
  image_cropper: ^4.0.1
  giphy_picker: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  emoji_picker_flutter: ^2.1.0
  sticky_headers: ^0.3.0+2
  path_provider: ^2.1.2
  image: ^4.1.7
  google_mobile_ads: ^5.0.0
  flutter_dotenv: ^5.1.0
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.1.1
  device_info_plus: ^9.1.2
  permission_handler: ^11.3.0
  grouped_list: ^5.1.2
  flutter_colorpicker: ^1.0.3
  encrypt: ^5.0.3
  flutter_datetime_picker_plus: ^2.1.0
  flutter_dynamic_icon: ^2.1.0
  flutter_android_dynamic_icon: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#F3FAFA"
  color_dark: "#151515"
  fullscreen: true
  image: assets/logos/ic_splash_new.png
  image_dark: assets/logos/ic_splash_new.png
  android: true
  android_12: 
    image: assets/logos/App-Android12-11521152_pixels.png
    image_dark: assets/logos/App-Android12-11521152_pixels.png
  ios: true
  web: false

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts: 
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets: 
    - assets/icons_app/
    - assets/images/ic_app_new.png
    - assets/logos/ic_launcher_new.png
    - assets/logos/ic_splash_new.png
    - lib/translations/locales/fr.json
    - lib/translations/locales/en.json
    - .env
