name: my_boilerplate
description: New flutter project with basics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.6.1
  flutter_native_splash: ^2.2.3+1
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  fullscreen: true
  image: assets/ic_splash.png
  image_dark: assets/ic_splash.png
  android: true
  ios: true
  web: false


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts: 
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets: 
    - assets/ic_splash.png
