name: myyoukounkoun
description: New flutter project with basics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_riverpod: ^2.1.3
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  country_code_picker: ^2.0.2
  image_picker: ^0.8.6
  colorful_safe_area: ^0.3.0
  url_launcher: ^6.1.6
  package_info_plus: ^3.0.1
  modal_bottom_sheet: ^2.1.2
  pin_code_fields: ^7.4.0
  flag: ^6.0.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^3.0.2
  age_calculator: ^1.0.0
  top_snackbar_flutter: ^3.0.0
  image_cropper: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  flutter_slidable: ^2.0.0
  emoji_picker_flutter: ^1.5.2
  giphy_picker: ^3.0.1
  sticky_headers: ^0.3.0+2
  image: ^4.0.15
  path_provider: ^2.0.12
  google_mobile_ads: ^2.3.0
  flutter_dotenv: ^5.0.2
  app_tracking_transparency: ^2.0.3
  device_info_plus: ^8.1.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/ic_launcher.png"
  web:
    generate: false

flutter_native_splash:
  fullscreen: true
  color: "#F3FAFA"
  color_dark: "#151515"
  image: assets/logos/ic_splash.png
  image_dark: assets/logos/ic_splash.png
  android12:
    color: "#F3FAFA"
    color_dark: "#151515"
    image: assets/logos/ic_splash.png
    image_dark: assets/logos/ic_splash.png
  android: true
  ios: true
  web: false


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts: 
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets: 
    - assets/images/ic_app.png
    - assets/logos/ic_launcher.png
    - assets/logos/ic_splash.png
    - lib/translations/locales/fr.json
    - lib/translations/locales/en.json
    - .env
