// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAShhIwreN2KkBd1v2KJNZouW9aaSmYxNo',
    appId: '1:878551705966:web:c72c5f651288ddd647797f',
    messagingSenderId: '878551705966',
    projectId: 'my-youkounkoun',
    authDomain: 'my-youkounkoun.firebaseapp.com',
    storageBucket: 'my-youkounkoun.appspot.com',
    measurementId: 'G-NS6M0C5J2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgUoTbuT_AiwC7uhGLBkoM70OoL9LenZw',
    appId: '1:878551705966:android:368b78954bcb95e447797f',
    messagingSenderId: '878551705966',
    projectId: 'my-youkounkoun',
    storageBucket: 'my-youkounkoun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgk7ToVHZiYKWpC6SQdYaWw_RgUrXDGI',
    appId: '1:878551705966:ios:286ac2e81713487f47797f',
    messagingSenderId: '878551705966',
    projectId: 'my-youkounkoun',
    storageBucket: 'my-youkounkoun.appspot.com',
    iosClientId: '878551705966-100n1573rj4023afervvfnijuobgieeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myyoukounkoun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgk7ToVHZiYKWpC6SQdYaWw_RgUrXDGI',
    appId: '1:878551705966:ios:286ac2e81713487f47797f',
    messagingSenderId: '878551705966',
    projectId: 'my-youkounkoun',
    storageBucket: 'my-youkounkoun.appspot.com',
    iosClientId: '878551705966-100n1573rj4023afervvfnijuobgieeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myyoukounkoun',
  );
}
